-- MySQL Script generated by MySQL Workbench
-- Sat Aug  1 20:41:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema `ciat_dw`
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciat_dw` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ciat_dw` ;


-- -----------------------------------------------------
-- Table `ciat_dw`.`dm_geographic_scope`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciat_dw`.`dm_geographic_scope` (
  `gscp_spk` INT(8) NOT NULL AUTO_INCREMENT,
  `gscp_id` BIGINT(20) NULL,
  `gscp_name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `gscp_definition` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `gscp_start_date` DATE NULL,
  `gscp_end_date` DATE NULL,
  `gscp_version` SMALLINT(4) NOT NULL,
  PRIMARY KEY (`gscp_spk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciat_dw`.`dm_research_program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciat_dw`.`dm_research_program` (
  `rprg_spk` INT(8) NOT NULL AUTO_INCREMENT,
  `rprg_id` BIGINT(20) NULL,
  `rprg_smo_code` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `rprg_name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `rprg_acronym` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `rprg_is_active` TINYINT(1) NULL,
  `rprg_start_date` DATE NULL,
  `rprg_end_date` DATE NULL,
  `rprg_version` SMALLINT(4) NOT NULL,
  PRIMARY KEY (`rprg_spk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciat_dw`.`dm_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciat_dw`.`dm_location` (
  `lct_spk` INT(8) NOT NULL AUTO_INCREMENT,
  `lct_id` BIGINT(20) NULL,
  `lct_name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `lct_iso_alpha_2` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `lct_iso_numeric` BIGINT(5) NULL,
  `lct_parent_id` BIGINT(20) NULL,
  `lct_is_region` TINYINT(1) NULL,
  `lct_is_active` TINYINT(1) NULL,
  `lct_start_date` DATE NULL,
  `lct_end_date` DATE NULL,
  `lct_version` SMALLINT(4) NOT NULL,
  PRIMARY KEY (`lct_spk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciat_dw`.`dm_development_outcome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciat_dw`.`dm_development_outcome` (
  `dotc_spk` INT(8) NOT NULL AUTO_INCREMENT,
  `dotc_id` BIGINT(20) NULL,
  `dotc_description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `dotc_ido_id` BIGINT(20) NULL,
  `dotc_smo_code` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `dotc_is_primary` TINYINT(1) NULL,
  `dotc_is_active` TINYINT(1) NULL,
  `dotc_start_date` DATE NULL,
  `dotc_end_date` DATE NULL,
  `dotc_version` SMALLINT(4) NOT NULL,
  PRIMARY KEY (`dotc_spk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciat_dw`.`dm_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciat_dw`.`dm_time` (
  `tme_spk` INT(8) NOT NULL,
  `tme_id` DATE NULL,
  `tme_description` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `tme_weekday_num` SMALLINT(1) NULL,
  `tme_weekday_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `tme_monthday_num` SMALLINT(2) NULL,
  `tme_month_num` SMALLINT(2) NULL,
  `tme_month_name` VARCHAR(50) NULL,
  `tme_quarter_num` SMALLINT(1) NULL,
  `tme_year` INT(4) NULL,
  `tme_is_weekend` TINYINT(1) NULL,
  PRIMARY KEY (`tme_spk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciat_dw`.`fact_policies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciat_dw`.`fact_policies` (
  `plc_spk` INT(8) NOT NULL AUTO_INCREMENT,
  `plc_id` BIGINT(20) NOT NULL,
  `plc_year` BIGINT(5) NULL,
  `plc_title` TEXT NULL,
  `plc_description` TEXT NULL,
  `plc_id_phase` BIGINT(20) NULL,
  `plc_is_active` TINYINT(1) NULL,
  `tme_spk` INT(8) NULL,
  `gscp_spk` INT(8) NULL,
  `rprg_spk` INT(8) NULL,
  `lct_spk` INT(8) NULL,
  `dotc_spk` INT(8) NULL,
  PRIMARY KEY (`plc_spk`)
  )
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


